name: delicias_online
description: Aplicativo de encomendas para a Confeitaria Delícias Online

# A versão do seu aplicativo (siga o padrão major.minor.patch+build)
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.6
  fluttertoast: ^8.2.2  # Para mostrar mensagens toast
  provider: ^6.0.5     # Para gerenciamento de estado
  shared_preferences: ^2.2.2  # Para armazenamento local
  intl: ^0.18.1        # Para formatação de datas/moedas
  mask_text_input_formatter: ^2.0.0 # Para máscaras em campos de texto
  geolocator: ^10.0.0  # Para obter localização GPS
  syncfusion_flutter_charts: ^20.3.56
  image_picker: ^0.8.6
  lottie: ^2.3.0
  iconsax: ^0.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  
  # Assets (imagens, fonts, etc)
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600